# Generated by Django 4.0.3 on 2022-04-24 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Davlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('davlat_nomi', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_nomi', models.CharField(max_length=128)),
                ('davlat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='restaurants.davlat')),
            ],
        ),
    ]
