# Generated by Django 4.0.3 on 2022-04-24 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_viloyat_restaurant_viloyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='viloyat',
            name='davlat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='restaurants.davlat'),
        ),
    ]
